// Pure catalog data — 156 print templates + 69 production-recipe workflows.
// No React / no engine runtime import (types only), so this module is safe to
// consume from the engine-only path. The React UI attaches thumbnails/handlers.
import type { NUpOptions, BookletOptions, TicketOptions, ResizeOptions } from './impose';

// Poster preset shape (mirrors the UI's local PosterOptions — kept here so the
// catalog has no dependency on the React layer).
interface PosterOptions {
  tilesAcross: number; tilesDown: number;
  sheetWIn: number; sheetHIn: number;
  overlapIn: number; addMarks: boolean; markLenIn: number; markOffIn: number;
  centerMarks?: boolean; markWeightPt?: number;
}

export interface TemplatePreset {
  nup?: Partial<NUpOptions>;
  booklet?: Partial<BookletOptions>;
  poster?: Partial<PosterOptions>;
  ticket?: Partial<TicketOptions>;
  resize?: Partial<ResizeOptions>;
}

export interface TemplateDef {
  id: string;
  name: string;
  industry: string;
  toolId: string;      // which tool this template opens
  specs: string;       // one-line size/finish summary
  preset?: TemplatePreset;
}

export const TEMPLATE_INDUSTRIES = [
  'Commercial Print', 'Packaging', 'Publishing', 'Large Format', 'Office', 'Variable Data', 'Real Estate',
];

export const TEMPLATES: TemplateDef[] = [
  // ── Commercial Print ──
  { id: "t000-10-up-business-cards", name: "10-Up Business Cards", industry: "Commercial Print", toolId: "business", specs: "Standard US business cards (3.5×2\") ganged 10-up on Letter with bleeds and crop marks.", preset: { nup: { cellWIn: 3.5, cellHIn: 2.0, sheetWIn: 8.5, sheetHIn: 11, bleedIn: 0.125, addMarks: true } } },
  { id: "t001-14-up-business-cards-tabloid", name: "14-Up Business Cards (Tabloid)", industry: "Commercial Print", toolId: "business", specs: "Production-run business cards ganged 14-up on 11×17\" tabloid for commercial offset.", preset: { nup: { cols: 2, rows: 7, sheetWIn: 11.0, sheetHIn: 17.0, addMarks: true } } },
  { id: "t002-2-up-door-hangers", name: "2-Up Door Hangers", industry: "Commercial Print", toolId: "gangsheet", specs: "Standard door hangers (3.875×8.75\") ganged 2-up on Letter with trim marks.", preset: { nup: { cols: 1, rows: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t003-2-up-gift-certificates-5-7", name: "2-Up Gift Certificates (5×7\")", industry: "Commercial Print", toolId: "coupons", specs: "5×7\" gift certificates, 2-up on Letter stock with crop marks." },
  { id: "t004-2-up-invitation-cards-5-7", name: "2-Up Invitation Cards (5×7\")", industry: "Commercial Print", toolId: "wedding", specs: "Wedding/event invitations (5×7\") printed 2-up on Letter with premium bleeds.", preset: { nup: { cols: 1, rows: 2, sheetWIn: 8.5, sheetHIn: 11, bleedIn: 0.125, addMarks: true } } },
  { id: "t005-2-up-notepad-sheets", name: "2-Up Notepad Sheets", industry: "Commercial Print", toolId: "ncrpads", specs: "Half-letter notepads (5.5×8.5\") printed 2-up on Letter (laid landscape) for padding.", preset: { nup: { cols: 2, rows: 1, sheetWIn: 11, sheetHIn: 8.5, addMarks: true } } },
  { id: "t006-2-up-postcards-4-6", name: "2-Up Postcards (4×6\")", industry: "Commercial Print", toolId: "postcard", specs: "USPS-standard 4×6\" postcards, 2-up on Letter for desktop or short-run digital.", preset: { nup: { cols: 1, rows: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t007-2-up-rack-cards-4-9", name: "2-Up Rack Cards (4×9\")", industry: "Commercial Print", toolId: "postcard", specs: "Standard rack cards for brochure holders, 2-up on tabloid stock.", preset: { nup: { cellWIn: 4.0, cellHIn: 9.0, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t008-3-up-door-hangers", name: "3-Up Door Hangers", industry: "Commercial Print", toolId: "gangsheet", specs: "3.5×8.5\" door hangers ganged 3-up across on Tabloid for die-cutting.", preset: { nup: { cols: 1, rows: 3, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t009-4-up-rack-cards-3-5-7", name: "4-Up Rack Cards (3.5×7\")", industry: "Commercial Print", toolId: "postcard", specs: "Vertical rack cards ganged 4-up on Tabloid. Standard tourism and retail display size (Letter cannot h…", preset: { nup: { cellWIn: 3.5, cellHIn: 7.0, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t010-4-up-ticket-strips", name: "4-Up Ticket Strips", industry: "Commercial Print", toolId: "raffle", specs: "Event/raffle tickets (8×2.5\") stacked 4-up on Letter with perforation marks." },
  { id: "t011-bi-fold-restaurant-menu", name: "Bi-Fold Restaurant Menu", industry: "Commercial Print", toolId: "menu", specs: "Standard bi-fold menu on Tabloid. Print both sides, fold in half for 4-panel menu." },
  { id: "t012-business-card-8-up-step-repeat", name: "Business Card 8-Up (Step & Repeat)", industry: "Commercial Print", toolId: "business", specs: "8-up step-and-repeat business cards using Expert Grid. All slots print the same card for maximum thro…", preset: { nup: { cols: 2, rows: 4, sheetWIn: 8.5, sheetHIn: 11, repeatFirst: true, addMarks: true } } },
  { id: "t013-business-cards-with-qr-code", name: "Business Cards with QR Code", industry: "Commercial Print", toolId: "business", specs: "10-up business cards on Letter with a QR code on the back — links to website or vCard.", preset: { nup: { sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t014-business-checks-3-up", name: "Business Checks (3-Up)", industry: "Commercial Print", toolId: "ncrpads", specs: "Standard 3-up business checks on Letter stock. MICR-safe layout with perforation marks.", preset: { nup: { cols: 1, rows: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t015-cd-tray-card-2-up", name: "CD Tray Card 2-Up", industry: "Commercial Print", toolId: "gangsheet", specs: "Standard CD jewel case tray cards (4.75×4.75\") ganged 2-up on Letter.", preset: { nup: { cols: 1, rows: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t016-certificate-2-up", name: "Certificate 2-Up", industry: "Commercial Print", toolId: "flyer", specs: "Award or training certificates 2-up on tabloid for desktop proofing or short-run printing.", preset: { nup: { cols: 1, rows: 2, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t017-compliment-slips-dl-3-up", name: "Compliment Slips (DL 3-Up)", industry: "Commercial Print", toolId: "complimentslip", specs: "DL compliment slips (210×99 mm) ganged 3-up, centered on an oversized SRA4 sheet with crop marks in t…", preset: { nup: { cols: 1, rows: 3, sheetWIn: 8.86, sheetHIn: 12.6, addMarks: true } } },
  { id: "t018-coupon-sheets-10-up", name: "Coupon Sheets (10-Up)", industry: "Commercial Print", toolId: "coupons", specs: "3.5×2\" coupons ganged 10-up on Letter with perforation-ready marks." },
  { id: "t019-eddm-postcard-6-25-9", name: "EDDM Postcard (6.25×9\")", industry: "Commercial Print", toolId: "postcard", specs: "USPS Every Door Direct Mail oversized postcard on 13×19\" stock.", preset: { nup: { cellWIn: 6.25, cellHIn: 9.0, sheetWIn: 13.0, sheetHIn: 19.0, addMarks: true } } },
  { id: "t020-folder-insert-tabloid", name: "Folder Insert (Tabloid)", industry: "Commercial Print", toolId: "presfolder", specs: "Presentation folder insert (9×12\") centered on tabloid with trim marks." },
  { id: "t021-full-bleed-brochure-booklet", name: "Full-Bleed Brochure Booklet", industry: "Commercial Print", toolId: "trifold", specs: "Add 3mm bleed to brochure pages, then impose as saddle-stitch booklet on Tabloid.", preset: { nup: { sheetWIn: 11, sheetHIn: 17, bleedIn: 0.125, addMarks: true } } },
  { id: "t022-full-bleed-postcards-4-up-bleed", name: "Full-Bleed Postcards (4-Up + Bleed)", industry: "Commercial Print", toolId: "postcard", specs: "Add 1/8″ bleed to postcard artwork missing bleeds, then gang 4-up on Letter with crop marks.", preset: { nup: { cols: 2, rows: 2, sheetWIn: 8.5, sheetHIn: 11, bleedIn: 0.125, addMarks: true } } },
  { id: "t023-gatefold-brochure-4-panel-letter", name: "Gatefold Brochure (4-Panel, Letter)", industry: "Commercial Print", toolId: "zfold", specs: "4-panel gatefold marketing brochure on Letter landscape. Two inner panels fold inward to meet at center.", preset: { nup: { sheetWIn: 11, sheetHIn: 8.5, addMarks: true } } },
  { id: "t024-loyalty-punch-cards-10-up", name: "Loyalty/Punch Cards (10-Up)", industry: "Commercial Print", toolId: "business", specs: "Standard business-card-size loyalty/punch cards, 10-up on Letter with crop marks.", preset: { nup: { cellWIn: 3.5, cellHIn: 2.0, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t025-ncr-form-3-part-carbon", name: "NCR Form (3-Part Carbon)", industry: "Commercial Print", toolId: "ncrpads", specs: "3-part carbonless form on Letter. Each part prints on separate sheet for collating.", preset: { nup: { sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t026-perfect-bound-a5-signatures", name: "Perfect Bound A5 Signatures", industry: "Commercial Print", toolId: "perfectbound", specs: "4-up perfect-bound book signatures for A5 trade paperbacks on A4 landscape.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t027-photo-contact-sheet-8-up", name: "Photo Contact Sheet (8-Up)", industry: "Commercial Print", toolId: "contact", specs: "Photographer's proof sheet with 8 images (2×4) on Letter. Quick client review layout.", preset: { nup: { cols: 2, rows: 4, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t028-postcard-2-up-work-turn", name: "Postcard 2-Up (Work & Turn)", industry: "Commercial Print", toolId: "postcard", specs: "2-up work-and-turn postcard imposition. Front and back print on the same sheet – flip along the short…", preset: { nup: { cols: 1, rows: 2, duplex: true, addMarks: true, duplexFlip: "long" } } },
  { id: "t029-proof-sheet-with-proof-watermark", name: "Proof Sheet with PROOF Watermark", industry: "Commercial Print", toolId: "contact", specs: "2-up proofing layout on Tabloid with a diagonal PROOF watermark — prevents client from using proofs a…", preset: { nup: { sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t030-rsvp-cards-4-up-3-5-5", name: "RSVP Cards (4-Up, 3.5×5\")", industry: "Commercial Print", toolId: "wedding", specs: "Response/RSVP cards (3.5×5\") printed 4-up on Letter with crop marks.", preset: { nup: { cellWIn: 3.5, cellHIn: 5.0, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t031-saddle-stitch-a4-magazine", name: "Saddle-Stitch A4 Magazine", industry: "Commercial Print", toolId: "magazine", specs: "32-page A4 magazine signatures on A3 landscape sheets for commercial offset.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t032-saddle-stitch-a5-booklet", name: "Saddle-Stitch A5 Booklet", industry: "Commercial Print", toolId: "booklet", specs: "Creates print-ready A5 saddle-stitched booklets from A5 source pages on A4 landscape sheets." },
  { id: "t033-shingled-3-up-cut-stack", name: "Shingled 3-Up (Cut & Stack)", industry: "Commercial Print", toolId: "cutstack", specs: "Classic cut-and-stack imposition for sequentially ordered pieces. Cut the stack into 3 strips and the…", preset: { nup: { cols: 1, rows: 3, cutStack: true, addMarks: true } } },
  { id: "t034-square-coasters-4-up", name: "Square Coasters (4-Up)", industry: "Commercial Print", toolId: "coasters", specs: "4\" square drink coasters printed 4-up on Tabloid stock with crop marks for die cutting.", preset: { nup: { cols: 2, rows: 2, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t035-step-and-repeat-flyer", name: "Step-and-Repeat Flyer", industry: "Commercial Print", toolId: "flyer", specs: "Fill a sheet with sequential flyer pages, auto-scaled to fit. Ideal for different-content handouts.", preset: { nup: { repeatFirst: true, addMarks: true } } },
  { id: "t036-tear-off-flyer-with-tabs", name: "Tear-Off Flyer with Tabs", industry: "Commercial Print", toolId: "magazine", specs: "Community bulletin flyer with tear-off contact tabs designed into the bottom of the artwork, placed 1…" },
  { id: "t037-tent-card-2-up", name: "Tent Card 2-Up", industry: "Commercial Print", toolId: "zfold", specs: "Fold-in-half table tent cards (4.25×5.5\" finished), 2-up on Letter for double-sided printing.", preset: { nup: { cols: 1, rows: 2, sheetWIn: 8.5, sheetHIn: 11, duplex: true, addMarks: true, duplexFlip: "long" } } },
  { id: "t038-tri-fold-brochure-letter", name: "Tri-Fold Brochure (Letter)", industry: "Commercial Print", toolId: "trifold", specs: "Standard tri-fold brochure on Letter stock. 6 panels (3 front, 3 back) with fold marks.", preset: { nup: { sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t039-tri-fold-brochure-2-up", name: "Tri-Fold Brochure 2-Up", industry: "Commercial Print", toolId: "trifold", specs: "Imposes two copies of each finished tri-fold brochure side on tabloid/A3-style duplex sheets.", preset: { nup: { cols: 1, rows: 2, sheetWIn: 11, sheetHIn: 17, duplex: true, addMarks: true, duplexFlip: "long" } } },
  { id: "t040-tri-fold-event-program", name: "Tri-Fold Event Program", industry: "Commercial Print", toolId: "trifold", specs: "Tri-fold event or church program on Letter landscape. 6 panels with fold marks.", preset: { nup: { sheetWIn: 11, sheetHIn: 8.5, addMarks: true } } },
  { id: "t041-wall-calendar-signatures", name: "Wall Calendar Signatures", industry: "Commercial Print", toolId: "perfectbound", specs: "Coil-bound wall calendar with back cover rotation on tabloid landscape.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t042-z-fold-accordion-6-panel-tabloid", name: "Z-Fold Accordion (6-Panel, Tabloid)", industry: "Commercial Print", toolId: "zfold", specs: "6-panel accordion-style brochure on 11×17\" tabloid. Zigzag folds, ~5.67\" per panel (17/3).", preset: { nup: { sheetWIn: 11.0, sheetHIn: 17.0, addMarks: true } } },
  // ── Packaging ──
  { id: "t043-bakery-tray-liner-1-up", name: "Bakery Tray Liner (1-Up)", industry: "Packaging", toolId: "packaging", specs: "Bakery/deli tray liners printed 1-up on Tabloid (two 10.5″ liners cannot stack on a 17″ sheet)." },
  { id: "t044-blister-card-4-up", name: "Blister Card 4-Up", industry: "Packaging", toolId: "packaging", specs: "Retail blister packaging cards (3.5×5\") ganged 4-up on Tabloid with dieline paths." },
  { id: "t045-box-flat-with-bleed-prep", name: "Box Flat with Bleed Prep", industry: "Packaging", toolId: "boxcarton", specs: "Add 5mm bleed to a box dieline flat, then resize to fit press sheet — ready for die-cutting." },
  { id: "t046-cd-dvd-jewel-case-wrap", name: "CD/DVD Jewel Case Wrap", industry: "Packaging", toolId: "packaging", specs: "Optical disc jewel case wrap (9.5×4.72\") on Tabloid with trim marks." },
  { id: "t047-candle-wraps-4-up", name: "Candle Wraps (4-Up)", industry: "Packaging", toolId: "labels", specs: "Candle label wraps (3×8\") printed 4-up on Tabloid for wrapping round candles.", preset: { nup: { cols: 2, rows: 2, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t048-candy-bar-wrappers-3-up", name: "Candy Bar Wrappers (3-Up)", industry: "Packaging", toolId: "packaging", specs: "Candy bar wraps (7.5×5.5\") placed 3-up on a 13×19″ press sheet for wrapping and gluing." },
  { id: "t049-envelope-flats-4-up-10", name: "Envelope Flats 4-Up (#10)", industry: "Packaging", toolId: "envelope", specs: "Standard #10 envelope flats (9.5×4.125\") ganged 4-up on Tabloid with dieline paths.", preset: { nup: { cols: 2, rows: 2, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t050-hang-tags-8-up-2-5-4", name: "Hang Tags 8-Up (2.5×4\")", industry: "Packaging", toolId: "hangtag", specs: "Retail garment hang tags ganged 8-up on Tabloid with die-cut contour paths.", preset: { nup: { cols: 2, rows: 4, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t051-lp-record-sleeve-insert", name: "LP Record Sleeve Insert", industry: "Packaging", toolId: "stickers", specs: "12×12\" vinyl record sleeve insert, 1-up on 13×19\" stock (12″ square cannot fit 2-up on a 13×19″ sheet).", preset: { nup: { sheetWIn: 13.0, sheetHIn: 19.0, addMarks: true } } },
  { id: "t052-pizza-box-lid-13-19", name: "Pizza Box Lid (13×19\")", industry: "Packaging", toolId: "boxcarton", specs: "10×10\" pizza box lid flat, 1-up on 13×19\" stock with trim marks (10″ square cannot fit 2-up)." },
  { id: "t053-poly-bag-headers-6-up", name: "Poly Bag Headers (6-Up)", industry: "Packaging", toolId: "packaging", specs: "Retail poly bag header cards (4×2.5\") printed 6-up on Letter with hang-hole marks." },
  { id: "t054-pouch-flats-2-up-tabloid", name: "Pouch Flats (2-Up Tabloid)", industry: "Packaging", toolId: "packaging", specs: "Stand-up pouch flats (6×9\") printed 2-up on landscape Tabloid for heat-seal pouches." },
  { id: "t055-seed-packets-6-up", name: "Seed Packets (6-Up)", industry: "Packaging", toolId: "envelope", specs: "Small seed packets (3×4.5\") ganged 6-up on Tabloid with crop marks (Letter cannot hold 3 rows of 4.5″…", preset: { nup: { cols: 2, rows: 3, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t056-shopping-bag-flat-2-up", name: "Shopping Bag Flat 2-Up", industry: "Packaging", toolId: "packaging", specs: "Retail shopping bag flats 2-up on Tabloid with fold and die-cut paths." },
  { id: "t057-soap-band-wraps-8-up", name: "Soap Band Wraps (8-Up)", industry: "Packaging", toolId: "packaging", specs: "Narrow soap bands (1.5×6\") ganged 8-up on Tabloid for bar soap wrapping (Letter cannot hold two 6″ ro…" },
  { id: "t058-soap-bar-wrap-4-up", name: "Soap Bar Wrap 4-Up", industry: "Packaging", toolId: "packaging", specs: "Body care product wraps (3×4\") ganged 4-up on Letter." },
  { id: "t059-tube-label-wrap-4-up", name: "Tube Label Wrap (4-Up)", industry: "Packaging", toolId: "labels", specs: "Cosmetic tube label wraps (6×2.5\") printed 4-up on a 13×19″ sheet for roll-on application.", preset: { nup: { cols: 2, rows: 2, sheetWIn: 13.0, sheetHIn: 19.0, addMarks: true } } },
  { id: "t060-wine-bottle-label-6-up", name: "Wine Bottle Label 6-Up", industry: "Packaging", toolId: "labels", specs: "Standard wine bottle labels (3.5×4\") ganged 6-up on Tabloid with trim marks.", preset: { nup: { cols: 2, rows: 3, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  // ── Publishing ──
  { id: "t061-16-page-church-bulletin-a4", name: "16-Page Church Bulletin (A4)", industry: "Publishing", toolId: "magazine", specs: "Saddle-stitched A4 bulletin on A3 landscape. Standard for weekly church programs." },
  { id: "t062-a5-pocket-book", name: "A5 Pocket Book", industry: "Publishing", toolId: "notebook", specs: "A5 (148×210mm) pocket paperback using saddle-stitch binding on A4 landscape." },
  { id: "t063-a5-saddle-stitch-2-up-on-sra3", name: "A5 Saddle-Stitch 2-Up on SRA3", industry: "Publishing", toolId: "booklet", specs: "Commercial A5 saddle-stitch workflow: impose each booklet side on SRA4, then repeat two copies on SRA3." },
  { id: "t064-children-s-book-8-5-square", name: "Children's Book (8.5\" Square)", industry: "Publishing", toolId: "booklet", specs: "Square-format picture book on Tabloid landscape with saddle-stitch binding." },
  { id: "t065-coloring-book-letter", name: "Coloring Book (Letter)", industry: "Publishing", toolId: "zine", specs: "US Letter coloring book with saddle-stitch binding. Single-sided interior (back pages blank)." },
  { id: "t066-concert-program-a5", name: "Concert Program (A5)", industry: "Publishing", toolId: "program", specs: "A5 saddle-stitched concert or theater program. 12-16 pages typical, fits in pocket." },
  { id: "t067-desk-calendar-tent-style", name: "Desk Calendar (Tent Style)", industry: "Publishing", toolId: "calendar", specs: "Desk tent calendar on Letter landscape with half-sheet layout." },
  { id: "t068-digest-magazine-5-5-8-5", name: "Digest Magazine (5.5×8.5\")", industry: "Publishing", toolId: "magazine", specs: "Reader's Digest-size magazine signatures. 4-up saddle-stitch on Tabloid.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t069-hymnal-songbook-a5", name: "Hymnal / Songbook (A5)", industry: "Publishing", toolId: "perfectbound", specs: "A5 hymnal or songbook with perfect binding on A4 stock. For churches and choirs.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t070-instruction-booklet-a6-4-up", name: "Instruction Booklet (A6 4-Up)", industry: "Publishing", toolId: "program", specs: "Small product instruction booklet. 4-up nested on A4 for cost-effective production." },
  { id: "t071-instruction-manual-a5", name: "Instruction Manual (A5)", industry: "Publishing", toolId: "program", specs: "A5 product instruction booklet, saddle-stitched on A4. Compact format for product packaging." },
  { id: "t072-landscape-wall-calendar", name: "Landscape Wall Calendar", industry: "Publishing", toolId: "calendar", specs: "Coil-bound wall calendar with back cover rotation on Tabloid landscape." },
  { id: "t073-lay-flat-photo-book-12-12", name: "Lay-Flat Photo Book (12×12\")", industry: "Publishing", toolId: "perfectbound", specs: "Square photo album with zero creep for lay-flat binding on 24×12\" stock.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t074-manga-rtl-comic-booklet", name: "Manga / RTL Comic Booklet", industry: "Publishing", toolId: "comic", specs: "Right-to-left saddle-stitched booklet for manga, Arabic, and Hebrew comics on B5 landscape.", preset: { booklet: { rtl: true } } },
  { id: "t075-memorial-funeral-program", name: "Memorial / Funeral Program", industry: "Publishing", toolId: "program", specs: "Half-letter memorial program, saddle-stitched on Letter landscape. Single fold, 4-8 pages." },
  { id: "t076-memorial-service-program", name: "Memorial Service Program", industry: "Publishing", toolId: "program", specs: "Half-letter bi-fold memorial program. 4 pages — cover, obituary spread, back." },
  { id: "t077-newsletter-4-page-single-fold", name: "Newsletter 4-Page (Single Fold)", industry: "Publishing", toolId: "gangsheet", specs: "Simple 4-page newsletter — one sheet folded in half on Letter landscape.", preset: { nup: { sheetWIn: 11, sheetHIn: 8.5, addMarks: true } } },
  { id: "t078-one-sheet-8-page-zine", name: "One-Sheet 8-Page Zine", industry: "Publishing", toolId: "zine", specs: "Classic fold-and-cut mini zine from 8 panels on one sheet. Print one-sided, cut the center slit, and…" },
  { id: "t079-perfect-bound-trade-paperback-4-up", name: "Perfect Bound Trade Paperback (4-Up)", industry: "Publishing", toolId: "perfectbound", specs: "4-up signatures for A5 perfect-bound trade paperbacks. Standard for novels, manuals, and catalogs.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t080-photo-book-landscape-a4", name: "Photo Book (Landscape A4)", industry: "Publishing", toolId: "perfectbound", specs: "Landscape A4 photo book with perfect binding. Full-bleed photo spreads.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t081-playbill-theater-program", name: "Playbill / Theater Program", industry: "Publishing", toolId: "program", specs: "A5 saddle-stitched theater program booklet on A4 stock." },
  { id: "t082-pocket-book-a6-from-a5", name: "Pocket Book (A6 from A5)", industry: "Publishing", toolId: "notebook", specs: "Small-format pocket book in A6 with 2-up perfect binding." },
  { id: "t083-pocket-digest-5-8", name: "Pocket Digest (5×8\")", industry: "Publishing", toolId: "perfectbound", specs: "5×8\" digest-size booklet using perfect binding. Common for literary journals and anthologies.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t084-quarter-letter-zine", name: "Quarter-Letter Zine", industry: "Publishing", toolId: "zine", specs: "Micro-zine at 4.25×5.5\" using 4-up saddle-stitch on Letter. Cut, fold, staple." },
  { id: "t085-recipe-book-letter", name: "Recipe Book (Letter)", industry: "Publishing", toolId: "perfectbound", specs: "US Letter recipe book with perfect binding. Ideal for cookbooks and recipe collections.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t086-saddle-stitch-a6-mini-booklet-8-up", name: "Saddle-Stitch A6 Mini Booklet (8-Up)", industry: "Publishing", toolId: "zine", specs: "8-up mini booklet for A6 saddle-stitched inserts and leaflets on A4." },
  { id: "t087-square-catalog-8-8", name: "Square Catalog (8×8\")", industry: "Publishing", toolId: "catalog", specs: "8×8\" square product catalog with saddle-stitch binding. Popular for retail and portfolio." },
  { id: "t088-student-planner-4-up", name: "Student Planner (4-Up)", industry: "Publishing", toolId: "perfectbound", specs: "A6 student planner pages imposed 4-up on A4 for perfect binding. 52+ weeks.", preset: { booklet: { signatureSheets: 4 } } },
  { id: "t089-us-comic-book-6-625-10-25", name: "US Comic Book (6.625×10.25\")", industry: "Publishing", toolId: "comic", specs: "Standard US comic book format on Tabloid with saddle-stitch binding." },
  { id: "t090-wedding-program", name: "Wedding Program", industry: "Publishing", toolId: "wedding", specs: "Half-letter (5.5×8.5\") wedding program booklet, saddle-stitched on Letter landscape.", preset: { nup: { sheetWIn: 11, sheetHIn: 8.5, addMarks: true } } },
  // ── Large Format ──
  { id: "t091-2-up-movie-posters-27-40", name: "2-Up Movie Posters (27×40\")", industry: "Large Format", toolId: "poster", specs: "Standard one-sheet cinema posters ganged 2-up on 54×40\" wide-format stock.", preset: { poster: { tilesAcross: 2, tilesDown: 1 } } },
  { id: "t092-4-up-18-24-posters", name: "4-Up 18×24\" Posters", industry: "Large Format", toolId: "poster", specs: "Four 18×24\" posters ganged on a 36×48\" sheet for screen printing or large-format digital.", preset: { poster: { tilesAcross: 4, tilesDown: 1 } } },
  { id: "t093-a-frame-sign-inserts", name: "A-Frame Sign Inserts", industry: "Large Format", toolId: "rollerbanner", specs: "Sidewalk A-frame sign inserts at 24×36\" with double-sided printing.", preset: { nup: { cols: 1, rows: 1, addMarks: false, sheetWIn: 24.0, sheetHIn: 36.0 } } },
  { id: "t094-banner-tiles-4-up-24-36-panels", name: "Banner Tiles 4-Up (24×36\" panels)", industry: "Large Format", toolId: "banner", specs: "Four 24×36\" banner panels on a single 96×36\" wide-format sheet for trade show displays.", preset: { poster: { tilesAcross: 4, tilesDown: 1 } } },
  { id: "t095-bus-shelter-poster-46-67", name: "Bus Shelter Poster (46×67\")", industry: "Large Format", toolId: "rollerbanner", specs: "Standard bus shelter/transit advertising poster at 46×67\" for backlit display.", preset: { nup: { cols: 1, rows: 1, addMarks: false, sheetWIn: 46.0, sheetHIn: 67.0 } } },
  { id: "t096-canvas-wrap-print-tiling", name: "Canvas Wrap Print Tiling", industry: "Large Format", toolId: "poster", specs: "Gallery-wrap canvas tiles auto-scaled in a 2×2 grid for large art prints." },
  { id: "t097-fabric-banner-24-72", name: "Fabric Banner (24×72\")", industry: "Large Format", toolId: "rollerbanner", specs: "Vertical fabric banner at 24×72\" for dye-sublimation printing.", preset: { nup: { cols: 1, rows: 1, addMarks: false, sheetWIn: 24.0, sheetHIn: 72.0 } } },
  { id: "t098-feather-flag-soft-signage", name: "Feather Flag (Soft Signage)", industry: "Large Format", toolId: "featherflag", specs: "Single-panel feather / teardrop flag artwork scaled to a Medium print area (700×2300 mm) for dye-subl…", preset: { nup: { cols: 1, rows: 1, addMarks: false } } },
  { id: "t099-floor-graphics-24-24", name: "Floor Graphics (24×24\")", industry: "Large Format", toolId: "stickers", specs: "Square floor decals at 24×24\" for retail wayfinding and promotional graphics.", preset: { nup: { cellWIn: 24.0, cellHIn: 24.0, addMarks: true } } },
  { id: "t100-menu-board-tabloid", name: "Menu Board (Tabloid)", industry: "Large Format", toolId: "menu", specs: "Restaurant menu board at 11×17\" Tabloid with color bar for print verification." },
  { id: "t101-real-estate-signs-24-36", name: "Real Estate Signs (24×36\")", industry: "Large Format", toolId: "rollerbanner", specs: "Large real estate signs at 24×36\" for property listings and open house signage.", preset: { nup: { cols: 1, rows: 1, addMarks: false, sheetWIn: 24.0, sheetHIn: 36.0 } } },
  { id: "t102-retractable-banner-33-80", name: "Retractable Banner (33×80\")", industry: "Large Format", toolId: "rollerbanner", specs: "Standard retractable/roll-up banner at 33×80\" for trade shows and events.", preset: { nup: { cols: 1, rows: 1, addMarks: false, sheetWIn: 33.0, sheetHIn: 80.0 } } },
  { id: "t103-step-and-repeat-photo-print", name: "Step-and-Repeat Photo Print", industry: "Large Format", toolId: "photo", specs: "Fill a sheet with identical photos. Perfect for passport photos, photo booth strips, and proofing.", preset: { nup: { repeatFirst: true, addMarks: true } } },
  { id: "t104-street-pole-banner-24-60", name: "Street Pole Banner (24×60\")", industry: "Large Format", toolId: "rollerbanner", specs: "Standard street/light pole banner at 24×60\" with bleed for pole pocket.", preset: { nup: { cols: 1, rows: 1, addMarks: false, sheetWIn: 24.0, sheetHIn: 60.0 } } },
  { id: "t105-table-runner-30-72", name: "Table Runner (30×72\")", industry: "Large Format", toolId: "rollerbanner", specs: "Conference table runner at 30×72\" for 6ft tables. Resized for large-format output.", preset: { nup: { cols: 1, rows: 1, addMarks: false, sheetWIn: 30.0, sheetHIn: 72.0 } } },
  { id: "t106-tiled-poster-a4-tiles-to-a0", name: "Tiled Poster (A4 tiles to A0)", industry: "Large Format", toolId: "poster", specs: "Tiles a large poster across multiple sheets. Each source page fills one cell in an 4×2 grid." },
  { id: "t107-trade-show-display-graphics", name: "Trade Show Display Graphics", industry: "Large Format", toolId: "poster", specs: "Exhibition pop-up display panels on 48×96\" wide-format with color bar for proofing." },
  { id: "t108-window-clings-a3", name: "Window Clings (A3)", industry: "Large Format", toolId: "rollerbanner", specs: "A3 (297×420mm) window cling graphics for storefront and vehicle windows.", preset: { nup: { cols: 1, rows: 1, addMarks: false } } },
  { id: "t109-yard-sign-24-18", name: "Yard Sign (24×18\")", industry: "Large Format", toolId: "rollerbanner", specs: "Standard coroplast yard sign at 24×18\" landscape for real estate, political, and event signage.", preset: { nup: { cols: 1, rows: 1, addMarks: false, sheetWIn: 24.0, sheetHIn: 18.0 } } },
  { id: "t110-yard-signs-18-24", name: "Yard Signs (18×24\")", industry: "Large Format", toolId: "rollerbanner", specs: "Corrugated yard signs at 18×24\" for real estate, political campaigns, and event signage.", preset: { nup: { cols: 1, rows: 1, addMarks: false, sheetWIn: 18.0, sheetHIn: 24.0 } } },
  // ── Office ──
  { id: "t111-2-sided-a5-flyer", name: "2-Sided A5 Flyer", industry: "Office", toolId: "flyer", specs: "Quick double-sided A5 flyer from your desktop printer. No marks, no bleeds — just fold or cut.", preset: { nup: { sheetWIn: 5.83, sheetHIn: 8.27, duplex: true, bleedIn: 0.125, addMarks: false, duplexFlip: "long" } } },
  { id: "t112-2-up-proofing-on-tabloid", name: "2-Up Proofing on Tabloid", industry: "Office", toolId: "overlay", specs: "Proof Letter-size artwork 2-up on Tabloid with crop marks to verify bleed and trim." },
  { id: "t113-4-up-index-cards-3-5", name: "4-Up Index Cards (3×5\")", industry: "Office", toolId: "trading", specs: "Study flashcards or index cards, 4-up on Letter for cutting.", preset: { nup: { cellWIn: 3.0, cellHIn: 5.0, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t114-add-page-numbers", name: "Add Page Numbers", industry: "Office", toolId: "pagenumbers", specs: "Adds \"Page X of Y\" to every page. Simple and universal — works with any PDF." },
  { id: "t115-binder-spine-labels-10-up", name: "Binder Spine Labels (10-Up)", industry: "Office", toolId: "labels", specs: "1\" binder spine labels printed 10-up on Letter. Standard 3-ring binder spine width.", preset: { nup: { cols: 2, rows: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t116-bookmarks-6-up", name: "Bookmarks (6-Up)", industry: "Office", toolId: "bookmark", specs: "Standard bookmarks (2×6\") printed 6-up on Letter stock.", preset: { nup: { cols: 2, rows: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t117-certificates-2-up", name: "Certificates (2-Up)", industry: "Office", toolId: "flyer", specs: "Half-letter classroom certificates printed 2-up on Letter for quick teacher printing.", preset: { nup: { cols: 1, rows: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t118-confidential-watermark", name: "Confidential Watermark", industry: "Office", toolId: "overlay", specs: "Red CONFIDENTIAL watermark for sensitive documents — visible but non-destructive." },
  { id: "t119-desk-name-plates-4-up", name: "Desk Name Plates (4-Up)", industry: "Office", toolId: "zfold", specs: "Folding desk name plates (8×2\" flat) printed 4-up on Letter.", preset: { nup: { cols: 2, rows: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t120-door-signs-2-up", name: "Door Signs (2-Up)", industry: "Office", toolId: "zfold", specs: "Do Not Disturb / office door signs (4×10\") printed 2-up on Letter.", preset: { nup: { cellWIn: 4.0, cellHIn: 10.0, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t121-draft-watermark", name: "Draft Watermark", industry: "Office", toolId: "overlay", specs: "Stamp a diagonal DRAFT watermark on every page — prevents accidental use of unfinished documents." },
  { id: "t122-emergency-contact-cards-10-up", name: "Emergency Contact Cards (10-Up)", industry: "Office", toolId: "business", specs: "Wallet-size emergency contact cards (3.5×2\") printed 10-up on Letter.", preset: { nup: { cols: 2, rows: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t123-flash-cards-12-up", name: "Flash Cards (12-Up)", industry: "Office", toolId: "trading", specs: "Study flash cards (3.5×2\") printed 12-up on Letter. Perfect for students and educators.", preset: { nup: { cols: 3, rows: 4, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t124-full-bleed-photo-cards-4-6", name: "Full-Bleed Photo Cards (4×6)", industry: "Office", toolId: "wedding", specs: "Add bleed to borderless photo cards, then print 2-up on Letter — perfect for holiday cards or invitat…", preset: { nup: { cellWIn: 4.0, cellHIn: 6.0, sheetWIn: 8.5, sheetHIn: 11, bleedIn: 0.125, addMarks: true } } },
  { id: "t125-greeting-card-a5-fold", name: "Greeting Card (A5 Fold)", industry: "Office", toolId: "greeting", specs: "Single-fold greeting card on Letter landscape. Print, fold in half, done." },
  { id: "t126-half-sheet-handout-2-up", name: "Half-Sheet Handout 2-Up", industry: "Office", toolId: "flyer", specs: "Two half-letter handouts per sheet. Perfect for meeting agendas, sign-up sheets, and flyers.", preset: { nup: { cols: 1, rows: 2, sheetWIn: 5.5, sheetHIn: 8.5, addMarks: true } } },
  { id: "t127-interleave-two-documents", name: "Interleave Two Documents", industry: "Office", toolId: "shuffle", specs: "Merges pages from two PDFs in alternating order (A1, B1, A2, B2...). Great for double-sided printing…" },
  { id: "t128-luggage-tags-6-up", name: "Luggage Tags (6-Up)", industry: "Office", toolId: "hangtag", specs: "Luggage tags (2.5×4.25\") printed 6-up on Letter with crop marks for die cutting.", preset: { nup: { cols: 2, rows: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t129-mailing-labels-avery-5160-style", name: "Mailing Labels (Avery 5160 Style)", industry: "Office", toolId: "labels", specs: "Address labels nested on Letter. Compatible with Avery 5160 and similar 30-up label sheets.", preset: { nup: { sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t130-mini-booklet-a7-zine", name: "Mini Booklet (A7 Zine)", industry: "Office", toolId: "zine", specs: "DIY mini zine using 4-up saddle-stitch on A4. Cut, fold, staple — instant pocket booklet." },
  { id: "t131-name-badges-8-up", name: "Name Badges (8-Up)", industry: "Office", toolId: "namebadge", specs: "Conference name badges (3.5×2.25\") printed 8-up on Letter for badge holders." },
  { id: "t132-parking-permits-4-up", name: "Parking Permits (4-Up)", industry: "Office", toolId: "hangtag", specs: "Parking permits / hang tags (3.5×5\") printed 4-up on Letter stock.", preset: { nup: { cols: 2, rows: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t133-place-cards-8-up", name: "Place Cards (8-Up)", industry: "Office", toolId: "wedding", specs: "Event place cards (3.5×2\") printed 8-up on Letter. Fold in half for tent-style seating cards.", preset: { nup: { cols: 2, rows: 4, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t134-proof-booklet-with-watermark", name: "Proof Booklet with Watermark", industry: "Office", toolId: "booklet", specs: "Saddle-stitch booklet on Letter with a PROOF watermark — for client review copies." },
  { id: "t135-raffle-tickets-8-up", name: "Raffle Tickets (8-Up)", industry: "Office", toolId: "raffle", specs: "Numbered raffle tickets (2×5.5\") printed 8-up on Letter with perforation marks." },
  { id: "t136-recipe-cards-4-6-4-up", name: "Recipe Cards (4×6\", 4-Up)", industry: "Office", toolId: "postcard", specs: "Standard recipe cards (4×6\") printed 4-up on Tabloid. Double-sided for ingredients + instructions.", preset: { nup: { cellWIn: 4.0, cellHIn: 6.0, sheetWIn: 11, sheetHIn: 17, duplex: true, addMarks: true, duplexFlip: "long" } } },
  { id: "t137-rotate-all-pages-landscape", name: "Rotate All Pages Landscape", industry: "Office", toolId: "rotate", specs: "Rotates all pages 90° clockwise. Useful for converting portrait scans to landscape." },
  { id: "t138-shipping-labels-6-up", name: "Shipping Labels (6-Up)", industry: "Office", toolId: "labels", specs: "Shipping/mailing labels (4×3.33\") printed 6-up on Letter. Fits standard label sheets.", preset: { nup: { cols: 2, rows: 3, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t139-tent-cards-4-up", name: "Tent Cards (4-Up)", industry: "Office", toolId: "zfold", specs: "Table tent cards (5×5\" flat, folds to 5×2.5\") printed 4-up on Letter.", preset: { nup: { cols: 2, rows: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t140-visitor-passes-10-up", name: "Visitor Passes (10-Up)", industry: "Office", toolId: "business", specs: "Business-card-size visitor passes (3.5×2\") printed 10-up on Letter stock.", preset: { nup: { cols: 2, rows: 5, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  // ── Variable Data ──
  { id: "t141-asset-tags-datamatrix", name: "Asset Tags (DataMatrix)", industry: "Variable Data", toolId: "namebadge", specs: "Compact DataMatrix asset tags, 10-up on Letter for inventory tracking." },
  { id: "t142-conference-badges-qr", name: "Conference Badges (QR)", industry: "Variable Data", toolId: "namebadge", specs: "Name badges with unique QR codes from CSV, 4-up on A4." },
  { id: "t143-event-tickets-qr-code", name: "Event Tickets (QR Code)", industry: "Variable Data", toolId: "tickets", specs: "QR code tickets from CSV data, 2-up on Letter sheets for easy cutting." },
  { id: "t144-gift-vouchers-qr-code", name: "Gift Vouchers (QR Code)", industry: "Variable Data", toolId: "coupons", specs: "Gift vouchers with unique QR redemption codes, 2-up on A4." },
  { id: "t145-loyalty-cards-code-128", name: "Loyalty Cards (Code 128)", industry: "Variable Data", toolId: "coupons", specs: "Loyalty/membership cards with unique Code 128 barcodes, 10-up on Letter." },
  { id: "t146-parking-permits-qr-code", name: "Parking Permits (QR Code)", industry: "Variable Data", toolId: "hangtag", specs: "Parking permits with unique QR validation codes, 4-up on Letter.", preset: { nup: { sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t147-product-labels-ean-13", name: "Product Labels (EAN-13)", industry: "Variable Data", toolId: "tickets", specs: "EAN-13 retail barcodes from CSV, 12-up on A4 for product labelling." },
  { id: "t148-raffle-tickets-numbered", name: "Raffle Tickets (Numbered)", industry: "Variable Data", toolId: "raffle", specs: "Code 128 barcode raffle tickets from CSV, 4-up on Letter." },
  { id: "t149-shipping-labels-code-128", name: "Shipping Labels (Code 128)", industry: "Variable Data", toolId: "tickets", specs: "Shipping labels with unique Code 128 barcodes, 10-up on Letter." },
  { id: "t150-wristbands-qr-code", name: "Wristbands (QR Code)", industry: "Variable Data", toolId: "coupons", specs: "Event wristbands with unique QR codes, 8-up on Letter." },
  // ── Real Estate ──
  { id: "t151-just-listed-flyer-2-up-8-5-5-5", name: "Just-Listed Flyer 2-Up (8.5×5.5\")", industry: "Real Estate", toolId: "flyer", specs: "Half-sheet landscape just-listed flyers, 2-up on Letter for feature sheets and open-house handouts.", preset: { nup: { cols: 2, rows: 1, sheetWIn: 11, sheetHIn: 8.5, addMarks: true } } },
  { id: "t152-just-listed-flyer-4-up-4-25-5-5", name: "Just-Listed Flyer 4-Up (4.25×5.5\")", industry: "Real Estate", toolId: "flyer", specs: "Quarter-sheet just-listed flyers, 4-up on Letter — the cheapest way to print open-house handouts.", preset: { nup: { cols: 2, rows: 2, sheetWIn: 8.5, sheetHIn: 11, addMarks: true } } },
  { id: "t153-just-sold-postcard-4-up-4-6", name: "Just-Sold Postcard 4-Up (4×6\")", industry: "Real Estate", toolId: "postcard", specs: "USPS-standard 4×6\" just-sold / farming postcards, 4-up on Tabloid for short-run direct mail.", preset: { nup: { cellWIn: 4.0, cellHIn: 6.0, sheetWIn: 11, sheetHIn: 17, addMarks: true } } },
  { id: "t154-open-house-yard-sign-2-up-18-24", name: "Open-House Yard Sign 2-Up (18×24\")", industry: "Real Estate", toolId: "rollerbanner", specs: "Two 18×24\" open-house / for-sale yard signs ganged on a 36×24\" large-format sheet.", preset: { nup: { cols: 2, rows: 1, sheetWIn: 36.0, sheetHIn: 24.0, addMarks: false } } },
  { id: "t155-property-brochure-tri-fold-2-up", name: "Property Brochure Tri-Fold 2-Up", industry: "Real Estate", toolId: "trifold", specs: "Imposes two copies of each finished property brochure side on tabloid duplex sheets with tri-fold cre…", preset: { nup: { cols: 1, rows: 2, sheetWIn: 11, sheetHIn: 17, duplex: true, addMarks: true, duplexFlip: "long" } } },
];

// ── Production-recipe workflows (pipeline step data) ──────────────────────────
export interface RecipeStep { kind: string; label: string; opts?: Record<string, unknown>; }
export interface RecipeDef { id: string; name: string; desc: string; cat: string; input: string; tip: string; tags: string[]; steps: RecipeStep[]; }
const s = (kind: string, label: string, opts?: Record<string, unknown>): RecipeStep => ({ kind, label, ...(opts ? { opts } : {}) });
const recipe = (cat: string, id: string, name: string, desc: string, steps: RecipeStep[], input: string, tip: string, tags: string[]): RecipeDef => ({ id, name, desc, cat, input, tip, tags, steps });
export const RECIPES: RecipeDef[] = [
  // ── Booklets & Books ──
  recipe('Booklets & Books', 'r-saddle', 'Saddle-Stitch Booklet', 'Standard saddle-stitched booklet — the most common short-run binding.', [s('preflight', 'Preflight'), s('booklet', 'Impose booklet'), s('cropmarks', 'Add trim marks')], 'Single PDF, sequential pages, count a multiple of 4, 3mm bleed.', 'Keep page count ≤ 64 for saddle-stitch; enable creep on stock heavier than 100gsm.', ['saddle-stitch', 'booklet', 'binding']),
  recipe('Booklets & Books', 'r-saddle-bleed', 'Saddle-Stitch with Bleeds', 'Saddle-stitch with synthetic bleed generation for artwork delivered without bleeds.', [s('preflight', 'Preflight'), s('bleed', 'Generate bleeds', { bleedIn: 0.125, mode: 'mirror' }), s('booklet', 'Impose booklet'), s('cropmarks', 'Add marks')], 'PDF at trim size (no bleed). Page count a multiple of 4.', 'Synthetic bleeds are a rescue technique, not a replacement for real bleeds — flag it on the job ticket.', ['saddle-stitch', 'bleed', 'no-bleed']),
  recipe('Booklets & Books', 'r-a5-sra3', 'A5 Saddle-Stitch 2-Up on SRA3', 'Impose A5 on SRA4 flats, then repeat two copies on SRA3.', [s('preflight', 'Preflight A5 pages'), s('booklet', 'Impose SRA4 booklet flats'), s('nup', 'Repeat 2-up on SRA3', { cols: 2, rows: 1, sheetWIn: 12.6, sheetHIn: 17.72 })], 'A5 portrait PDF, sequential reading order, preferably 3mm bleed.', 'Use Grid step-and-repeat (adapts to any booklet page count); SRA4 is exactly half of SRA3.', ['a5', 'sra3', '2-up']),
  recipe('Booklets & Books', 'r-perfect', 'Perfect-Bound Book', 'PUR/hot-melt perfect binding for books with 48+ pages.', [s('preflight', 'Preflight'), s('booklet', 'Impose signatures', { creepIn: 0 }), s('collating', 'Add collating marks'), s('cropmarks', 'Add trim marks')], 'Single PDF, sequential, 3mm bleed, CMYK. Count divisible by 8/16/32.', 'Leave 5mm extra at the spine edge for PUR milling; confirm signature count with your bindery.', ['perfect-binding', 'PUR', 'signatures']),
  recipe('Booklets & Books', 'r-perfect-cb', 'Perfect-Bound with Color Bar', 'Perfect-bound signatures with inline color bars for press density control.', [s('booklet', 'Impose signatures', { creepIn: 0 }), s('colorbar', 'Add color bars'), s('collating', 'Add collating marks'), s('cropmarks', 'Add trim marks')], 'CMYK PDF, 3mm bleed, page count divisible by 16.', 'Color bars need ≥ 8mm of non-image area along the gripper edge — verify plate size.', ['perfect-binding', 'color-bar', 'offset']),
  recipe('Booklets & Books', 'r-casebound', 'Case-Bound (Hardcover) Book', 'Smyth-sewn case-bound book with signature imposition and spine marks.', [s('preflight', 'Preflight'), s('booklet', 'Impose signatures'), s('gathering', 'Add gathering marks'), s('cropmarks', 'Add trim marks')], 'Text-block PDF, sequential, 3mm bleed, CMYK. Cover supplied separately.', 'Case-bound needs a separate cover imposition; add 3mm to the spine-side bleed for Smyth-sewing.', ['case-bound', 'hardcover', 'smyth-sewn']),
  recipe('Booklets & Books', 'r-zine', 'Zine / Mini Booklet', 'Small-format DIY zine from a single sheet (8-page or 16-page fold).', [s('resize', 'Scale pages'), s('booklet', 'Impose as booklet'), s('foldmarks', 'Add fold marks')], '8-page or 16-page PDF at final reading size.', 'For a single-sheet 8-page zine, print duplex, cut a centre slit and fold — verify with a paper dummy.', ['zine', 'mini-booklet', 'fold']),
  recipe('Booklets & Books', 'r-comic', 'Comic Book Signatures', 'Comic/graphic novel imposed in saddle-stitch or perfect-bound signatures.', [s('preflight', 'Preflight'), s('colormanage', 'Convert to CMYK'), s('booklet', 'Impose booklet'), s('cropmarks', 'Add trim marks')], 'Sequential pages at comic trim size + 3mm bleed. RGB or CMYK.', 'US comic trim is 6.625×10.25"; manga is typically B6 (128×182mm). Confirm with the publisher spec.', ['comic', 'graphic-novel', 'manga']),
  recipe('Booklets & Books', 'r-childrens', "Children's Book", 'Full-color picture book with heavy stock and case binding.', [s('preflight', 'Preflight'), s('booklet', 'Impose signatures'), s('colorbar', 'Add color bars'), s('cropmarks', 'Add trim marks')], 'Full-color CMYK PDF, min 300 DPI, 5mm bleed for board books.', "Board books need special imposition — each 'page' is two laminated sheets; confirm with the bindery.", ['childrens-book', 'picture-book', 'case-bound']),
  recipe('Booklets & Books', 'r-photobook', 'Photo Book', 'Lay-flat photo book with flush-mount or perfect binding.', [s('preflight', 'Preflight'), s('colormanage', 'Color convert'), s('booklet', 'Impose signatures'), s('cropmarks', 'Add trim marks')], 'High-res CMYK or sRGB PDF with 3mm bleed. Even page count.', 'Lay-flat requires page pairs printed as spreads — a gutter gap will ruin panoramic photos.', ['photo-book', 'lay-flat', 'flush-mount']),
  recipe('Booklets & Books', 'r-magazine', 'Magazine Production', 'Full commercial magazine with saddle-stitch or perfect binding and press marks.', [s('preflight', 'Preflight'), s('booklet', 'Impose signatures'), s('colorbar', 'Add color bars'), s('cropmarks', 'Add marks')], 'Complete magazine PDF, sequential, CMYK, 3mm bleed, fonts embedded.', 'Ads from multiple sources have inconsistent color — verify TIC does not exceed 340% for heatset web.', ['magazine', 'web-offset', 'commercial']),
  recipe('Booklets & Books', 'r-catalog', 'Catalog Signatures', 'Multi-signature catalog for perfect binding on commercial presses.', [s('booklet', 'Impose signatures'), s('gathering', 'Add gathering marks'), s('collating', 'Add collating marks'), s('cropmarks', 'Add trim marks')], 'CMYK PDF, page count divisible by signature size, 3mm bleed.', 'Large catalogs (200+ pages) benefit from 32-up if your press handles the sheet — fewer signatures = fewer errors.', ['catalog', 'signatures', 'gathering']),
  recipe('Booklets & Books', 'r-annual', 'Annual Report', 'Corporate annual report with mixed content and premium finishing.', [s('preflight', 'Preflight'), s('booklet', 'Impose signatures'), s('colorbar', 'Add color bars'), s('cropmarks', 'Add marks')], 'CMYK + spot color PDF, 3mm bleed, fonts embedded, transparency flattened.', 'If it mixes coated and uncoated stocks, impose each stock type separately and coordinate signature order.', ['annual-report', 'corporate', 'spot-color']),

  // ── Cards & Flat ──
  recipe('Cards & Flat', 'r-bizcard', 'Business Cards', 'Standard multi-up business card layout on a press sheet.', [s('nup', 'Impose cards', { cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11, marginIn: 0.25, gutterIn: 0.125 }), s('cropmarks', 'Add cut marks')], 'Business card PDF at trim size with 3mm bleed. Duplex as pages 1 & 2.', 'Standard sizes: 3.5×2" (US), 85×55mm (EU), 91×55mm (AU/NZ). Pull bleeds from the document.', ['business-cards', 'multi-up', 'cutting']),
  recipe('Cards & Flat', 'r-bizcard-nb', 'Business Cards (No-Bleed Rescue)', 'Business cards from artwork delivered without bleeds.', [s('bleed', 'Generate bleeds', { bleedIn: 0.125, mode: 'mirror' }), s('nup', 'Impose cards', { cellWIn: 3.5, cellHIn: 2, sheetWIn: 8.5, sheetHIn: 11 }), s('cropmarks', 'Add cut marks')], 'Business card PDF at exact trim size, no bleed.', 'Synthetic bleeds on edge-to-edge photos show mirrored artefacts — request proper bleeds when possible.', ['business-cards', 'no-bleed', 'rescue']),
  recipe('Cards & Flat', 'r-postcard', 'Postcards', 'Multi-up postcards (4×6 or A6) on press sheets.', [s('nup', 'Impose postcards', { cellWIn: 6, cellHIn: 4, sheetWIn: 13, sheetHIn: 19 }), s('cropmarks', 'Add marks')], 'Postcard PDF at trim size, front and back pages, 3mm bleed.', 'USPS requires min 3.5×5" and specific barcode clear zones for mailable postcards.', ['postcards', 'direct-mail', 'multi-up']),
  recipe('Cards & Flat', 'r-greeting', 'Greeting Cards', 'Folded greeting cards imposed for duplex printing and fold finishing.', [s('booklet', 'Impose as booklet'), s('foldmarks', 'Add fold marks'), s('cropmarks', 'Add trim marks')], '4-page PDF in reading order at final folded size with 3mm bleed.', 'Greeting cards are typically 4 pages (front, inside-L, inside-R, back) — the booklet tool reorders spreads.', ['greeting-cards', 'folded', 'score']),
  recipe('Cards & Flat', 'r-playing', 'Playing Cards', 'Full deck of playing cards imposed for sheet-fed printing.', [s('nup', 'Grid layout', { cols: 5, rows: 4, sheetWIn: 13, sheetHIn: 19 }), s('registration', 'Add registration'), s('cropmarks', 'Add cut marks')], '54 cards as individual pages, poker size (63×88mm) with 3mm bleed.', 'Playing cards need exact front-to-back registration or the back pattern reveals the face at the edges.', ['playing-cards', 'die-cut', 'registration']),
  recipe('Cards & Flat', 'r-doorhanger', 'Door Hangers', 'Multi-up door hangers with a die-cut hook hole.', [s('nup', 'Grid layout'), s('cutcontour', 'Add die contour'), s('cropmarks', 'Add marks')], 'Door hanger PDF at trim size with die-cut hook area marked. 3mm bleed.', 'Standard door hanger is 4.25×11". Use the cut-contour tool to define the hook die precisely.', ['door-hangers', 'die-cut', 'multi-up']),
  recipe('Cards & Flat', 'r-rackcard', 'Rack Cards', '4×9 inch rack cards imposed for multi-up printing.', [s('nup', 'Impose rack cards', { cellWIn: 4, cellHIn: 9, sheetWIn: 13, sheetHIn: 19 }), s('cropmarks', 'Add marks')], 'Rack card PDF at 4×9" trim size with 3mm bleed.', 'Rack cards have a narrow aspect — run the grain parallel to the long edge for stiffness.', ['rack-cards', 'display', 'multi-up']),
  recipe('Cards & Flat', 'r-numticket', 'Numbered Tickets', 'Sequential numbered tickets with cut-and-stack imposition.', [s('shuffle', 'Shuffle for cut-and-stack'), s('nup', 'Grid layout'), s('cropmarks', 'Add marks')], 'PDF with one page per ticket, sequentially numbered. Count divisible by grid cells.', 'Cut-and-stack numbering needs the shuffle order to match your guillotine cut sequence — verify with a test sheet.', ['tickets', 'numbered', 'cut-and-stack']),
  recipe('Cards & Flat', 'r-vdticket', 'Variable Data Tickets', 'Tickets with variable data (barcodes, names, seats) imposed efficiently.', [s('barcode', 'Add barcodes'), s('nup', 'Grid layout'), s('cropmarks', 'Add marks')], 'PDF with one ticket per page, each containing unique variable data.', 'Variable data tickets need each barcode unique and scannable — verify readability at final printed size.', ['tickets', 'VDP', 'barcode']),
  recipe('Cards & Flat', 'r-wedding', 'Wedding Invitations', 'Premium invitations with RSVP cards and envelopes imposed together.', [s('passthrough', 'Merge components'), s('nest', 'Gang on sheet'), s('cropmarks', 'Add marks')], 'Separate PDFs for each suite component (invite, RSVP, details), each at trim size with bleed.', 'Wedding suites often include multiple card sizes — gang them so all pieces print in the same pass with identical color.', ['wedding', 'gang', 'suite']),

  // ── Labels & Stickers ──
  recipe('Labels & Stickers', 'r-sticker-sheet', 'Sticker Sheets', 'Full sticker sheets with kiss-cut contours for peel-and-stick.', [s('nest', 'Nest stickers'), s('cutcontour', 'Add die lines', { spotName: 'KissCut', dashed: true }), s('registration', 'Add registration')], 'Individual sticker artwork as separate pages. 1mm bleed around each.', 'Kiss-cut depth penetrates the vinyl/paper but NOT the liner; keep ≥ 3mm padding for plotter tracking.', ['stickers', 'kiss-cut', 'nesting']),
  recipe('Labels & Stickers', 'r-diecut-sticker', 'Die-Cut Stickers', 'Individual die-cut stickers (through-cut, no backing sheet).', [s('nest', 'Nest stickers'), s('cutcontour', 'Add thru-cut contour', { spotName: 'ThruCut' }), s('cropmarks', 'Add marks')], 'Individual sticker designs, one per page, at final size with 1mm bleed.', 'Thru-cut on vinyl needs a slightly oversized cut path (0.5mm offset) to avoid white borders from misregistration.', ['die-cut', 'stickers', 'thru-cut']),
  recipe('Labels & Stickers', 'r-productlabel', 'Product Labels', 'Multi-up product labels for bottles, jars and boxes.', [s('nup', 'Grid layout'), s('colorbar', 'Add color bar'), s('cutcontour', 'Add die marks')], 'Label PDF at flat die size with 2mm bleed. CMYK + spot if brand-critical.', 'Labels for curved surfaces (bottles) need distortion compensation — confirm values with the applicator vendor.', ['product-labels', 'bottles', 'brand']),
  recipe('Labels & Stickers', 'r-shipping', 'Shipping Labels', 'Shipping labels (4×6") on self-adhesive A4/Letter sheets.', [s('nup', 'Grid layout', { cellWIn: 6, cellHIn: 4 }), s('barcode', 'Add barcodes')], '4×6" label PDF per shipment, one page per label.', 'Shipping labels are usually thermal-printed; for offset/digital use a label-stock template and align to the die exactly.', ['shipping', 'barcode', 'logistics']),
  recipe('Labels & Stickers', 'r-address', 'Address Labels', 'Avery-style address labels on standard label sheets.', [s('nup', 'Grid layout', { cellWIn: 2.625, cellHIn: 1, sheetWIn: 8.5, sheetHIn: 11, marginIn: 0.1875, addMarks: false }), s('cropmarks', 'Add guides', { markLenIn: 0.1 })], 'Individual label content, one per page, at the Avery cell size.', 'Pre-die-cut label stock needs exact registration — test-print on plain paper and hold against a sheet first.', ['address-labels', 'Avery', 'mail-merge']),
  recipe('Labels & Stickers', 'r-vinyl', 'Vinyl Stickers', 'Outdoor-rated vinyl stickers with laminate overprint and contour cut.', [s('nest', 'Nest on material'), s('cutcontour', 'Add cut contour'), s('registration', 'Add registration')], 'Sticker artwork on transparent background (PNG/PDF) at final size.', 'For outdoor vinyl add a 2mm white border to prevent edge peel; use solvent or UV-cure inks only.', ['vinyl', 'outdoor', 'contour-cut']),
  recipe('Labels & Stickers', 'r-qrlabel', 'QR Code Labels', 'Unique QR code labels for product tracking or authentication.', [s('qrstamp', 'Generate QR codes'), s('nup', 'Grid layout'), s('cropmarks', 'Add marks')], 'One QR code per page, or a data file for batch generation. Label size specified.', 'QR codes need min 15mm at print resolution; add error-correction level H (30%) for labels that may get scratched.', ['QR-code', 'labels', 'tracking']),
  recipe('Labels & Stickers', 'r-coaster', 'Coasters', 'Printed coasters (round or square) imposed for die cutting.', [s('nup', 'Grid layout'), s('cutcontour', 'Add die contour', { shape: 'ellipse' }), s('cropmarks', 'Add marks')], 'Coaster artwork at die size (typically 95mm round/square) with 3mm bleed.', 'Coaster board (1.4mm pulpboard) absorbs ink differently — reduce TIC to 280% and expect color shift.', ['coasters', 'die-cut', 'pulpboard']),

  // ── Packaging ──
  recipe('Packaging', 'r-box', 'Box Layout', 'Folding carton box flat (die-line) with artwork positioned for die cutting.', [s('passthrough', 'Apply die template'), s('cutcontour', 'Add cut contour'), s('cropmarks', 'Add marks')], 'Flat artwork matching the die-line exactly. Die-line supplied as a separate overlay PDF.', "Always work from the die-maker's approved CAD file — even 0.5mm off can jam the gluing machine.", ['box', 'folding-carton', 'die-line']),
  recipe('Packaging', 'r-labelwrap', 'Label Wrap', 'Wraparound labels for bottles/cans/tubes with distortion compensation.', [s('distort', 'Apply distortion'), s('nup', 'Multi-up layout'), s('cropmarks', 'Add marks')], 'Flat label artwork at unwrapped dimensions with 2mm bleed. Specify diameter.', 'distortion% = (thickness / (diameter/2 + thickness)) × 100. Round containers need only circumferential distortion.', ['label-wrap', 'bottle', 'distortion']),
  recipe('Packaging', 'r-corrugated', 'Corrugated Packaging', 'Large-format corrugated box or display printed on flatbed or flexo.', [s('distort', 'Flexo distortion'), s('colormanage', 'Color convert'), s('cropmarks', 'Add marks')], 'Artwork on the corrugated die flat. Spot colors preferred. Verify flute direction.', 'Corrugated print is low resolution (65-100 LPI) — simplify halftones, min type 8pt, avoid reverses < 10pt.', ['corrugated', 'flexo', 'large-format']),
  recipe('Packaging', 'r-bag', 'Bag Layout', 'Paper or poly bag printed flat and imposed for production.', [s('passthrough', 'Apply bag template'), s('nup', 'Multi-up'), s('cropmarks', 'Add marks')], 'Flat bag artwork with fold lines marked. Gusset panels if applicable.', 'Bag printing wraps around fold edges; side gusset panels are often printed in mirror — verify with a folding dummy.', ['bag', 'poly-bag', 'packaging']),
  recipe('Packaging', 'r-sleeve', 'Sleeve / Band', 'Shrink sleeves or belly bands for product packaging.', [s('distort', 'Shrink distortion'), s('nup', 'Multi-up layout'), s('registration', 'Add registration')], 'Flat sleeve artwork at pre-shrink dimensions. Specify shrink material and container.', 'Shrink sleeves distort differently circumferentially vs vertically — get the exact shrink ratios from your converter.', ['sleeve', 'shrink-sleeve', 'gravure']),
  recipe('Packaging', 'r-envelope', 'Envelope Layout', 'Printed envelopes imposed for flatbed or rotary die cutting.', [s('passthrough', 'Apply envelope template'), s('nup', 'Multi-up'), s('cutcontour', 'Add die lines')], 'Envelope artwork on the flat die layout with fold flaps. Die template as overlay.', 'Envelope flaps must be oriented for the fold direction — print on the inside of the flap if the design wraps the seal.', ['envelope', 'die-cut', 'mail']),

  // ── Large Format ──
  recipe('Large Format', 'r-poster', 'Poster Tiling', 'Large poster split into printable tiles with overlap for assembly.', [s('passthrough', 'Split into tiles'), s('cropmarks', 'Add marks')], 'Single-page PDF at full poster size (e.g. 24×36" or A0). 150-300 DPI.', 'Use 10-15mm overlap between tiles; align the tile grid to avoid splitting faces/text across a seam.', ['poster', 'tiling', 'assembly']),
  recipe('Large Format', 'r-banner', 'Banner Printing', 'Wide-format banners with tiling for roll-fed printers.', [s('resize', 'Scale to size'), s('passthrough', 'Tile if needed'), s('cropmarks', 'Add marks')], 'Single PDF at final banner size or at 1/4 scale. Specify dimensions.', 'Banners viewed at 3+ metres need only 72-100 DPI; vinyl banners need a 25mm hemming allowance.', ['banner', 'wide-format', 'vinyl']),
  recipe('Large Format', 'r-signage', 'Signage Repeat', 'Repeated signage (shelf talkers, aisle signs) ganged on large-format sheets.', [s('nup', 'Step-and-repeat'), s('cropmarks', 'Add cut marks')], 'Single sign PDF at trim size with 3mm bleed. Specify substrate sheet dimensions.', 'For rigid substrates add 3mm bleed beyond the cut; the CNC router kerf is 2-3mm — account for it in gutters.', ['signage', 'step-and-repeat', 'rigid']),
  recipe('Large Format', 'r-tradeshow', 'Trade Show Panels', 'Multi-panel trade show displays split for separate printing and assembly.', [s('passthrough', 'Split into panels'), s('resize', 'Scale panels'), s('cropmarks', 'Add guides')], 'Full continuous artwork at the assembled display size. Specify frame system + panel count.', 'Trade-show frame systems have pockets that add 25-50mm per side — get exact frame specs before sizing panels.', ['trade-show', 'panels', 'display']),
  recipe('Large Format', 'r-floor', 'Floor Graphics', 'Floor decals and wayfinding graphics with contour cutting.', [s('resize', 'Scale to size'), s('cutcontour', 'Add cut contour'), s('registration', 'Add registration')], 'Floor graphic artwork at final size. Include 10mm bleed for contour shapes.', 'Floor graphics must be laminated with anti-slip overlaminate (ASTM D2047) — always specify the laminate.', ['floor-graphics', 'contour-cut', 'safety']),
  recipe('Large Format', 'r-vehicle', 'Vehicle Wrap', 'Vehicle wrap panels split for contour-cut application.', [s('passthrough', 'Split into panels'), s('resize', 'Verify scale'), s('cropmarks', 'Add panel marks')], 'Full vehicle artwork on a professional template. Panels pre-separated or as one flat.', 'Vehicle wraps need 50-75mm extra per panel for wrapping edges — use a professional template, not hand-measured.', ['vehicle-wrap', 'vinyl', 'large-format']),

  // ── Production Marks ──
  recipe('Production Marks', 'r-fullmarks', 'Full Press Marks', 'Complete press mark set for commercial offset production.', [s('cropmarks', 'Crop & fold marks'), s('registration', 'Registration targets'), s('colorbar', 'Color control bar'), s('jobslug', 'Job info slug')], 'Already-imposed press sheet PDF ready for mark application.', 'Standard mark set for any commercial offset job — place marks ≥ 3mm from trim and keep them from overlapping.', ['press-marks', 'offset', 'registration']),
  recipe('Production Marks', 'r-digitalready', 'Digital Press Ready', 'Mark set optimized for digital presses (HP Indigo, Xerox iGen).', [s('cropmarks', 'Trim marks'), s('colorbar', 'Color bar')], 'Imposed PDF, any tool. CMYK with transparency flattened.', 'Digital presses have built-in registration — focus on color bars and trim marks to keep the DFE file simple.', ['digital-press', 'HP-Indigo', 'Xerox']),
  recipe('Production Marks', 'r-offsetready', 'Offset Press Ready', 'Full offset press preparation with all required finishing marks.', [s('cropmarks', 'Full trim marks'), s('registration', 'Registration marks'), s('colorbar', 'Color bar'), s('passthrough', 'Lay marks')], 'Imposed press-sheet PDF, CMYK, transparency flattened, fonts embedded.', 'Verify the plate accommodates all marks — on CTP workflows marks are often added by the CTP software.', ['offset', 'CTP', 'commercial-print']),
  recipe('Production Marks', 'r-saddlefinish', 'Saddle-Stitch Finishing Marks', 'Finishing marks specifically for saddle-stitch bindery operations.', [s('cropmarks', 'Trim marks'), s('foldmarks', 'Fold marks'), s('collating', 'Collating marks')], 'Imposed saddle-stitch signatures, ready for finishing marks.', 'The saddle-stitch line reads collating marks optically — ensure high contrast and consistent placement.', ['saddle-stitch', 'finishing', 'collating']),
  recipe('Production Marks', 'r-pbfinish', 'Perfect Bind Finishing Marks', 'Finishing marks for perfect binding with gathering verification.', [s('cropmarks', 'Trim marks'), s('gathering', 'Gathering marks'), s('passthrough', 'OMR marks')], 'Imposed perfect-bind signatures with known signature thickness.', 'OMR and gathering marks serve different purposes — gathering is visual, OMR is machine-verified. Use both on high-volume runs.', ['perfect-bind', 'gathering', 'OMR']),
  recipe('Production Marks', 'r-diecutmarks', 'Die-Cut Production Marks', 'Complete die-cutting mark set for labels, stickers and packaging.', [s('cutcontour', 'Die contour'), s('registration', 'Registration marks'), s('cropmarks', 'Sheet marks')], 'Artwork with die-line paths on separate spot-color layers, imposed on the press sheet.', 'Use industry layer naming: CutContour, KissCut, Crease, Perforation — automated cutters recognise these from the metadata.', ['die-cut', 'contour', 'packaging']),
  recipe('Production Marks', 'r-proofwm', 'Watermarked Proof', 'Draft proof with watermark and job info for client approval.', [s('watermark', 'Add watermark', { text: 'PROOF', opacity: 0.15 }), s('jobslug', 'Add proof info')], 'Any PDF at any stage. This is a proofing overlay, not production output.', 'Always watermark proofs before sending to clients — an unwatermarked proof has reached press in every shop.', ['proof', 'watermark', 'approval']),
  recipe('Production Marks', 'r-brandedproof', 'Branded Proof', "Client proof with your shop's branding, job info and color patches.", [s('watermark', 'Add proof watermark', { text: 'PROOF' }), s('headerfooter', 'Add header/footer'), s('colorbar', 'Add reference bar')], 'PDF to be proofed, at any stage of production.', "Include your shop's ICC profile name in the footer so the client can identify the proofing condition.", ['proof', 'branded', 'approval']),

  // ── Calendars & Specialty ──
  recipe('Calendars & Specialty', 'r-wallcal', 'Wall Calendar', '12-month wall calendar with saddle-stitch or wire-o binding.', [s('passthrough', 'Generate calendar'), s('booklet', 'Impose for binding'), s('cropmarks', 'Add marks')], '13-page PDF (cover + 12 months) in landscape with 3mm bleed.', 'Wall calendars need a hanging hole — add a drill mark top-center; wire-o is preferred so pages lay flat.', ['calendar', 'wall-calendar', 'wire-o']),
  recipe('Calendars & Specialty', 'r-deskcal', 'Desk Calendar', 'Desk tent calendar with fold-and-stand construction.', [s('passthrough', 'Generate calendar'), s('nup', 'Impose as cards'), s('foldmarks', 'Add fold marks')], '13-page PDF at the flat (unfolded) desk size with 3mm bleed.', 'Desk calendars fold in half to stand — the base half is usually blank; ensure front/back align for the fold.', ['calendar', 'desk-calendar', 'tent']),
  recipe('Calendars & Specialty', 'r-planner', 'Planner / Diary', 'Wire-o or perfect-bound planner with weekly/daily layouts.', [s('preflight', 'Preflight'), s('booklet', 'Impose signatures'), s('cropmarks', 'Add marks')], 'Complete planner PDF, sequential, 3mm bleed. Count divisible by signature size.', 'Wire-o planners need a 12mm margin on the bind side for wire holes; perfect-bound need 5mm spine milling.', ['planner', 'diary', 'wire-o']),
  recipe('Calendars & Specialty', 'r-menu', 'Restaurant Menu', 'Folded restaurant menu (bi-fold, tri-fold, or booklet).', [s('booklet', 'Impose as booklet'), s('foldmarks', 'Add fold marks'), s('cropmarks', 'Add trim marks')], 'Menu PDF in reading-order pages, final folded size with 3mm bleed.', 'Menus on heavy stock (300gsm+) must be scored before folding or the paper cracks — add scoring marks.', ['menu', 'restaurant', 'score']),
  recipe('Calendars & Specialty', 'r-newsletter', 'Newsletter', 'Folded newsletter (4-8 pages) for mailing or distribution.', [s('booklet', 'Impose booklet'), s('headerfooter', 'Add mailing panel'), s('cropmarks', 'Add marks')], '4-page or 8-page newsletter PDF in reading order, folded size, 3mm bleed.', 'For self-mailers the address panel must meet USPS regulations: clear zone around the barcode, correct fold-edge placement.', ['newsletter', 'self-mailer', 'mailing']),
  recipe('Calendars & Specialty', 'r-envprod', 'Envelope Production', 'Printed envelopes imposed and prepared for envelope-making machinery.', [s('passthrough', 'Apply die template'), s('nup', 'Multi-up'), s('cropmarks', 'Add marks')], 'Flat envelope artwork on the die-maker template with fold flaps.', 'Window envelopes need the window precisely registered to the letter fold — test with the actual insert.', ['envelope', 'die-cut', 'production']),

  // ── Ganging & Optimization ──
  recipe('Ganging & Optimization', 'r-mixedgang', 'Mixed Gang Run', 'Multiple different jobs ganged on a single press sheet for cost efficiency.', [s('passthrough', 'Merge jobs'), s('nest', 'Gang on sheet'), s('cropmarks', 'Add marks')], 'Multiple job PDFs at their individual trim sizes with bleed. Same stock and coating.', 'Gang runs share ink density — group items with similar color requirements (e.g. all warm tones together).', ['gang', 'multi-job', 'cost-saving']),
  recipe('Ganging & Optimization', 'r-gangfull', 'Gang Run with Full Marks', 'Ganged production sheet with complete finishing marks for commercial press.', [s('nest', 'Gang items'), s('colorbar', 'Add color bar'), s('cropmarks', 'Add all marks'), s('jobslug', 'Add job info')], 'Multiple production-ready PDFs, trimmed to final size with 3mm bleed. Same substrate.', 'Number each ganged item in the slug so the cutter operator can verify all pieces after cutting.', ['gang', 'full-marks', 'commercial']),
  recipe('Ganging & Optimization', 'r-expertcustom', 'Expert Custom Imposition', 'Fully custom imposition using Expert Grid for non-standard layouts.', [s('passthrough', 'Custom grid layout'), s('cropmarks', 'Add marks')], 'Source pages ready for custom positioning. Know your press sheet size and grid requirements.', 'Expert Grid is the escape hatch for layouts no standard tool handles — plan your grid on paper first.', ['expert', 'custom', 'imposition']),
  recipe('Ganging & Optimization', 'r-expertfinish', 'Expert Grid with Finishing', 'Custom Expert Grid imposition with full finishing marks.', [s('passthrough', 'Custom layout'), s('colorbar', 'Add color bar'), s('cropmarks', 'Add marks'), s('registration', 'Add registration')], 'Source pages and a detailed imposition plan (grid spec, gutter widths, rotations).', 'Verify finishing marks do not overlap the grid cells — custom gutters may be narrower than the mark footprint.', ['expert', 'finishing', 'production']),
  recipe('Ganging & Optimization', 'r-cutstacknum', 'Cut-and-Stack Numbering', 'Sequential numbering with cut-and-stack page ordering for tickets, NCR or raffle books.', [s('shuffle', 'Cut-and-stack shuffle'), s('nup', 'Grid layout'), s('cropmarks', 'Add marks')], 'PDF with one page per numbered item, sequentially numbered. Count = grid cells × sheet count.', 'The shuffle order MUST match your cutting sequence (top-to-bottom then left-to-right). Verify a test sheet first.', ['cut-and-stack', 'numbering', 'NCR']),

  // ── Transform & Prep ──
  recipe('Transform & Prep', 'r-printready', 'Print-Ready Preparation', 'Standard pre-flight and preparation workflow for incoming files.', [s('preflight', 'Preflight check'), s('colormanage', 'Color convert'), s('optimize', 'Optimize')], 'Any incoming PDF from a client or designer. No specific format required.', 'First-pass workflow for every incoming file — run preflight first, then convert and optimize. Never skip preflight.', ['preflight', 'print-ready', 'first-pass']),
  recipe('Transform & Prep', 'r-preflightfix', 'Preflight and Fix', 'Identify and repair common PDF issues before production.', [s('preflight', 'Identify issues'), s('repair', 'Repair PDF'), s('optimize', 'Optimize')], 'Problematic PDF that crashes, shows errors, or renders incorrectly.', 'If repair fails the file may be too damaged — re-save as PDF/X in Acrobat, or distill from PostScript as a last resort.', ['preflight', 'repair', 'troubleshoot']),
  recipe('Transform & Prep', 'r-multimerge', 'Multi-File Merge', 'Merge multiple source files into a single document for unified processing.', [s('passthrough', 'Merge files'), s('resize', 'Normalize size')], 'Multiple PDFs to be combined. Specify the desired page order.', 'Merge order becomes page order — double-check the sequence; convert to a common color profile before merging.', ['merge', 'multi-file', 'consolidate']),
  recipe('Transform & Prep', 'r-duplex', 'Duplex Interleave', 'Interleave separate front and back files for duplex printing.', [s('passthrough', 'Interleave fronts and backs'), s('resize', 'Normalize dimensions')], 'Two PDFs: one with all fronts, one with all backs. Both must have the same page count.', 'If the back file is in reverse order (common from scanning), reverse it first — one page off cascades through the whole job.', ['duplex', 'interleave', 'two-sided']),
  recipe('Transform & Prep', 'r-worktumble', 'Work and Tumble', 'Flip backup for the work-and-tumble duplex printing method.', [s('flip', 'Flip for tumble', { direction: 'v' }), s('cropmarks', 'Add marks')], 'Imposed front-side sheet ready for tumble backup creation.', 'Work-and-tumble flips along the short edge; work-and-turn along the long edge — the wrong flip mirrors the backs.', ['work-and-tumble', 'duplex', 'flip']),
  recipe('Transform & Prep', 'r-landscape', 'Landscape Rotation', 'Rotate pages from portrait to landscape (or vice versa) for press feed direction.', [s('rotate', 'Rotate pages', { angleDeg: 90 }), s('passthrough', 'Verify dimensions')], 'PDF with pages in the wrong orientation for the target press.', 'Confirm rotation direction (CW vs CCW) with a test page — the wrong rotation puts the gripper edge on the wrong side.', ['rotate', 'landscape', 'orientation']),
  recipe('Transform & Prep', 'r-flexo', 'Flexo Distortion', 'Pre-distort artwork for flexographic plate mounting on cylinders.', [s('distort', 'Apply distortion'), s('colormanage', 'Convert to flexo profile'), s('registration', 'Add registration')], 'Artwork at 1:1 undistorted size. Specify plate thickness and cylinder repeat length.', 'D% = (plate thickness × π / repeat length) × 100. Always get these values from the plate maker.', ['flexo', 'distortion', 'plate']),
];
